export const VOZ_LIVING_INIT = 'VOZ_LIVING_INIT';
export const VOZ_LIVING_GET_THREAD_LIST = 'VOZ_LIVING_GET_THREAD_LIST';
export const VOZ_LIVING_CHANGE_OPTION = 'VOZ_LIVING_CHANGE_OPTION';
export const VOZ_LIVING_UDATE_QUOTE_LIST = 'VOZ_LIVING_UDATE_QUOTE_LIST';
export const VOZ_LIVING_SEEN_ALL_QUOTE = 'VOZ_LIVING_SEEN_ALL_QUOTE';
