export const VOZ_LIVING_INIT = 'VOZ_LIVING_INIT';
export const VOZ_LIVING_GET_THREAD_LIST = 'VOZ_LIVING_GET_THREAD_LIST';
export const VOZ_LIVING_UDATE_QUOTE_LIST = 'VOZ_LIVING_UDATE_QUOTE_LIST';
export const VOZ_LIVING_SEEN_ALL_QUOTE = 'VOZ_LIVING_SEEN_ALL_QUOTE';
export const VOZ_LIVING_ADD_QUICK_LINK = 'VOZ_LIVING_ADD_QUICK_LINK';
export const VOZ_LIVING_UPDATE_QUICK_LINK = 'VOZ_LIVING_UPDATE_QUICK_LINK';
export const VOZ_LIVING_SAVE_QUICK_LINK = 'VOZ_LIVING_SAVE_QUICK_LINK';
export const VOZ_LIVING_REMOVE_QUICK_LINK = 'VOZ_LIVING_REMOVE_QUICK_LINK';
export const VOZ_LIVING_UPDATE_POST_TRACKER = 'VOZ_LIVING_UPDATE_POST_TRACKER';
export const VOZ_LIVING_THREAD_SUBSCRIBE = 'VOZ_LIVING_THREAD_SUBSCRIBE';
export const VOZ_LIVING_THREAD_UNSUBSCRIBE = 'VOZ_LIVING_THREAD_UNSUBSCRIBE';
export const VOZ_LIVING_SAVE_POST = 'VOZ_LIVING_SAVE_POST';
export const VOZ_LIVING_UNSAVE_POST = 'VOZ_LIVING_UNSAVE_POST';

export const VOZ_LIVING_UPDATE_PAGE_STATUS_ID = 'VOZ_LIVING_UPDATE_PAGE_STATUS_ID';