const emotions = [{
  text: ':sexy:',
  src: '/images/smilies/Off/sexy_girl.gif',
}, {
  text: ':byebye:',
  src: '/images/smilies/Off/byebye.gif',
}, {
  text: ':look_down:',
  src: '/images/smilies/Off/look_down.gif',
}, {
  text: ':stick:',
  src: '/images/smilies/Off/burn_joss_stick.gif',
}, {
  text: ':adore:',
  src: '/images/smilies/Off/adore.gif',
}, {
  text: ':nosebleed:',
  src: '/images/smilies/Off/nosebleed.gif',
}, {
  text: ':beauty:',
  src: '/images/smilies/Off/beauty.gif',
}, {
  text: ':gach:',
  src: 'images/smilies/brick.png',
}, {
  text: ':">',
  src: '/images/smilies/Off/embarrassed.gif',
}, {
  text: ':surrender:',
  src: '/images/smilies/Off/surrender.gif',
}, {
  text: ':pudency:',
  src: '/images/smilies/Off/pudency.gif',
}, {
  text: ':sosad:',
  src: '/images/smilies/Off/too_sad.gif',
}, {
  text: ':chaymau:',
  src: '/images/smilies/Off/nosebleed.gif',
}, {
  text: ':go:',
  src: '/images/smilies/Off/go.gif',
}, {
  text: ':sweat:',
  src: '/images/smilies/Off/sweat.gif',
}, {
  text: ':canny:',
  src: '/images/smilies/Off/canny.gif',
}, {
  text: ':sogood:',
  src: '/images/smilies/Off/feel_good.gif',
}, {
  text: ':shame:',
  src: '/images/smilies/Off/shame.gif',
}, {
  text: ':hungry:',
  src: '/images/smilies/Off/hungry.gif',
}, {
  text: ':shot:',
  src: '/images/smilies/Off/beat_shot.gif',
}, {
  text: ':rap:',
  src: '/images/smilies/Off/rap.gif',
}, {
  text: ':hang:',
  src: '/images/smilies/Off/hang.gif',
}, {
  text: ':*',
  src: '/images/smilies/Off/sweet_kiss.gif',
}, {
  text: ':ops:',
  src: '/images/smilies/Off/ops.gif',
}, {
  text: ':)',
  src: '/images/smilies/Off/smile.gif',
}, {
  text: ':plaster:',
  src: '/images/smilies/Off/beat_plaster.gif',
}, {
  text: ':tire:',
  src: '/images/smilies/Off/tire.gif',
}, {
  text: ':brick:',
  src: '/images/smilies/Off/beat_brick.gif',
}, {
  text: ':badsmell:',
  src: '/images/smilies/Off/bad_smelly.gif',
}, {
  text: ':hell_boy:',
  src: '/images/smilies/Off/hell_boy.gif',
}, {
  text: ':kool:',
  src: '/images/smilies/Off/cool.gif',
}, {
  text: ':dribble:',
  src: '/images/smilies/Off/dribble.gif',
}, {
  text: ':waaaht:',
  src: '/images/smilies/Off/waaaht.gif',
}, {
  text: ':oh:',
  src: '/images/smilies/Off/oh.gif',
}, {
  text: ':((',
  src: '/images/smilies/Off/cry.gif',
}, {
  text: '^:)^',
  src: '/images/smilies/Off/lay.gif',
}, {
  text: ':aboom:',
  src: '/images/smilies/Off/after_boom.gif',
}, {
  text: ':sad:',
  src: '/images/smilies/Off/sad.gif',
}, {
  text: ':hug:',
  src: '/images/smilies/Off/hug.gif',
}, {
  text: ':fix:',
  src: '/images/smilies/Off/fix.gif',
}, {
  text: ':amazed:',
  src: '/images/smilies/Off/amazed.gif',
}, {
  text: ':shitty:',
  src: '/images/smilies/Off/shit.gif',
}, {
  text: ':what:',
  src: '/images/smilies/Off/what.gif',
}, {
  text: ':cheers:',
  src: '/images/smilies/Off/cheers.gif',
}, {
  text: '-_-',
  src: '/images/smilies/Off/sleep.gif',
}, {
  text: ':spam:',
  src: '/images/smilies/Off/spam.gif',
}, {
  text: ':ah:',
  src: '/images/smilies/Off/ah.gif',
}, {
  text: ':rofl:',
  src: '/images/smilies/Off/rofl.gif',
}, {
  text: ':baffle:',
  src: '/images/smilies/Off/baffle.gif',
}, {
  text: ':choler:',
  src: '/images/smilies/Off/choler.gif',
}, {
  text: ':doubt:',
  src: '/images/smilies/Off/doubt.gif',
}, {
  text: ':capture:',
  src: '/images/smilies/Off/capture.gif',
}, {
  text: ':confident:',
  src: '/images/smilies/Off/confident.gif',
}, {
  text: ':theft:',
  src: '/images/smilies/Off/theft.gif',
}, {
  text: ':matrix:',
  src: '/images/smilies/Off/matrix.gif',
}, {
  text: ':haha:',
  src: '/images/smilies/Off/haha.gif',
}, {
  text: ':hehe:',
  src: '/images/smilies/Off/hehe.gif',
}, {
  text: ':smoke:',
  src: '/images/smilies/Off/smoke.gif',
}, {
  text: ':D',
  src: '/images/smilies/Off/big_smile.gif',
}, {
  text: ':angry:',
  src: '/images/smilies/Off/angry.gif',
}, {
  text: ':sos:',
  src: '/images/smilies/Off/sos.gif',
}, {
  text: ':spiderman:',
  src: '/images/smilies/Off/spiderman.gif',
}, {
  text: ':boss:',
  src: '/images/smilies/Off/boss.gif',
}, {
  text: ':dreaming:',
  src: '/images/smilies/Off/still_dreaming.gif',
}, {
  text: ':-s',
  src: '/images/smilies/Off/confuse.gif',
}, {
  text: ':bike:',
  src: '/images/smilies/Off/bike.gif',
}, {
  text: ':misdoubt:',
  src: '/images/smilies/Off/misdoubt.gif',
}, {
  text: ':mage:',
  src: '/images/smilies/Off/mage.gif',
}, {
  text: ':bye:',
  src: '/images/smilies/Off/bye.gif',
}, {
  text: ':phone:',
  src: '/images/smilies/Off/phone.gif',
}, {
  text: ':lmao:',
  src: '/images/smilies/Off/lmao.gif',
}, {
  text: ':ot:',
  src: '/images/smilies/Off/ot.gif',
}, {
  text: ':flame:',
  src: '/images/smilies/Off/flame.gif',
}, {
  text: ':bang:',
  src: '/images/smilies/Off/bang.gif',
}, {
  text: ':sure:',
  src: '/images/smilies/Off/sure.gif',
}, {
  text: ':stupid:',
  src: '/images/smilies/emos/stupid.gif',
}, {
  text: ':ban:',
  src: '/images/smilies/Off/bann.gif',
}, {
  text: ':doublegun:',
  src: '/images/smilies/emos/doublegun.gif',
}, {
  text: ':boom:',
  src: '/images/smilies/emos/boom.gif',
}, {
  text: ':lol:',
  src: '/images/smilies/emos/lol.gif',
}, {
  text: ':welcome:',
  src: '/images/smilies/Off/welcome.gif',
}, {
  text: ':please:',
  src: '/images/smilies/Off/please.gif',
}, {
  text: ':puke:',
  src: '/images/smilies/emos/puke.gif',
}, {
  text: ':shit:',
  src: '/images/smilies/emos/shit.gif',
}, {
  text: ':lovemachine:',
  src: '/images/smilies/emos/lovemachine.gif',
}, {
  text: ':runrun:',
  src: '/images/smilies/Off/runrun.gif',
}, {
  text: ':loveyou:',
  src: '/images/smilies/emos/loveyou.gif',
}, {
  text: ':Birthday:',
  src: '/images/smilies/emos/Birthday.gif',
}, {
  text: ':no:',
  src: '/images/smilies/emos/no.gif',
}, {
  text: ':yes:',
  src: '/images/smilies/emos/yes.gif',
}, {
  text: ':shoot1:',
  src: '/images/smilies/emos/shoot1.gif',
}, {
  text: ':winner:',
  src: '/images/smilies/emos/winner.gif',
}, {
  text: ':band:',
  src: '/images/smilies/emos/band.gif',
}, {
  text: ':grin:',
  src: '/images/smilies/biggrin.gif',
}, {
  text: ':frown:',
  src: '/images/smilies/frown.gif',
}, {
  text: ':mad:',
  src: '/images/smilies/mad.gif',
}, {
  text: ':p',
  src: '/images/smilies/tongue.gif',
}, {
  text: ':embrass:',
  src: '/images/smilies/redface.gif',
}, {
  text: ':confused:',
  src: '/images/smilies/confused.gif',
}, {
  text: ';)',
  src: '/images/smilies/wink.gif',
}, {
  text: ':rolleyes:',
  src: '/images/smilies/rolleyes.gif',
}, {
  text: ':cool:',
  src: '/images/smilies/cool.gif',
}, {
  text: ':eek:',
  src: '/images/smilies/eek.gif',
}];

export default emotions;
